- index.js
- index.test.js
- serve.py
- wsgi.py
This PR enables having a an WSGI app in a module below the root where the `serverless.yml` is (e.g. `app/api.py`), in order to allow a more flexible structure, specially when having multiple functions in the same service.
> enable package inside module

- index.js
- index.test.js
- wsgi.py
This PR packages the `.requirements` directory inside the `appPath`. This approach allows better dependency encapsulation when using multiple functions in the same service.
> Packages requirements inside function directory

- wsgi.py
So we can use lambda info such as  `context.log_group_name` and `context.log_stream_name`.
> Adds context to request environ

- wsgi.py
Anything returned from Flask in Python v3.6.1 (now supported by Lambda) seems to return a byte string ('bytes') rather than a string.
This causes the serialization of the return dictionary to fail in awslambda/bootstrap.py.
This patch checks for a byte string, and if it exists, serializes it to be safely passed back to API gateway.
Note that Zappa has a similar implementation that seems to always serialize bytes due to a fault in their logic that always returns true:
See: https://github.com/Miserlou/Zappa/blob/master/zappa/handler.py#L433-L442
> Support for 'bytes' response.data

- requirements.py
- requirements_test.py
Hi!
Some thing strange with working on Mac OS and Python3.6 (Anaconda). When deploy it fails with a bad python_dir path.
I am interested in continuing developing this plugin, please contact me if you need any help.
> Fix python directory for python3.6 on mac os

- index.js
- index.test.js
Upon cleanup, don't remove the `.requirements/` directory if the user has set `packRequirements: true`.
I like to use the [serverless-python-requirements](https://github.com/UnitedIncome/serverless-python-requirements) plugin to manage Python dependencies in my Serverless services. The cross-compiling feature is really helpful, plus it's nice to use the same requirements tool for all my Serverless services, even non-Flask ones.
Because of this, I set `packRequirements: false` in my `serverless.yml` file. This causes serverless-wsgi to avoid installing the requirements, but it still tries to clean up the `.requirements/` directory [here](https://github.com/logandk/serverless-wsgi/blob/9dc67c74b06f117259a6b18999852dc3ff7a45e1/index.js#L83-L88).
I found [this …
> Don't cleanup .requirements/ if packRequirements: false

- README.md
- wsgi.py
- wsgi_test.py
When using serverless-wsgi with a custom domain on API Gateway, I might have a [base path mapping](http://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html#how-to-custom-domains-mapping-console) (e.g. `/users` or `/prod`). This was being send to the WSGI application in the path. As a result, my Flask app couldn't find the proper path to handle the request.
This fixes that if you set the `API_GATEWAY_BASE_PATH` environment variable.
> Add configuration for handling base path mappings

- index.js
Hi, just wanted to say I'm a big fan of serverless-wsgi, it's super useful.
Anyway, I was running into an edge case when using this library in conjunction with the serverless-python-requirements . That library also uses a .requirements folder, but expects it to be excluded, whereas this library forces it to be included. This means when I deploy, all the python libs are included twice in my package, doubling the deploy size. It seems to make sense to me that serverless-wsgi shouldn't try to include the .requirements folder if it isn't doing any packaging. 
Let me know what you think.
> Only add .requirements folder to includes when packing enabled.

- CHANGELOG.md
- README.md
- index.js
- index.test.js
- package-lock.json
- package.json
- wsgi.py
* Package requirements into service root directory in order to avoid munging
sys.path to load requirements (#30).
* Package requirements when deploying individual non-WSGI functions (#30).
* Added `pythonBin` option to set python executable, defaulting to current runtime version (#29).
> Improve requirement packaging

- serve.py
Adds an `IS_OFFLINE` environment variable when running locally with `sls wsgi serve`.
It's often useful to know when you're developing locally, such as when configuring the boto3 client to work with a local DynamoDB emulator using [serverless-dynamodb-local](https://github.com/99xt/serverless-dynamodb-local). I chose to use `IS_OFFLINE` as it mirrors the same env variable used in [serverless-offline](https://github.com/dherault/serverless-offline), which is a popular local emulator for NodeJS apps.
> Add IS_OFFLINE environment variable to serve

- wsgi.py
- wsgi_test.py
Hi there! Thanks so much for developing and maintaining this amazing plugin!
I ran into an issue lately when handling binary data in Lambda with serverless-wsgi and thought I'd submit a PR to fix it:
Issue
- When working with binary request payloads, API Gateway passes the request body into the lambda as base64-encoded data, and serverless-wsgi didn't have any checking for decoding it.
- When using compressed responses such as gzip-encoded JSON, serverless-wsgi treated it as a "text MIME type", passing it along to API gateway without properly base64-encoding it.
Solution
- Check the `event` for API Gateway's `isBase64Encoded` attribute, and decode the body if needed.
- Make sure any encoding is done before the new content-length is calculated.
- Check for a `Content-Encoding` in the …
> Fix handling of binary request payloads and compressed responses.

- index.js
- index.test.js
`before:deploy:createDeploymentArtifacts` and `after:deploy:createDeploymentArtifacts` are both deprecated, switch to using `before:package:createDeploymentArtifacts` and `after:package:createDeploymentArtifacts`, respectively.
Resolves #38
> Update Deprecated Hooks

- package-lock.json
- wsgi.py
- wsgi_test.py
Fixes #45.
I looked at [how Zappa handles binary content](https://github.com/Miserlou/Zappa/blob/master/zappa/wsgi.py#L69-L81), and I think this fix will work. Previously, we would do the `wsgi_encoding_dance()` and conversion `to_bytes()` on _all_ bodies, regardless of their content. Now, we only do that dance + conversion if the body is a string type. If the body is a bytes object, it will remain as is.
I had to change a test since the `Content-Length` is now different. It now is the same on Python 2 & 3 🎉. However, I don't know enough about encodings to know for sure that this won't break other things.
In addition to running the unit tests, I also confirmed this worked with my app where I was experiencing this problem.
> Fix body encoding

- wsgi.py
This allows proper output (not base64-encoded) when using
django-rest-framework-json-api.
> Add 'application/vnd.api+json' to MIME_TYPES

- .gitignore
- index.js
- index.test.js
- serve.py
- serve_test.py
I like to configure my projects to run on Docker so I can easily test things locally by adding the missing pieces (database, cache, etc) to my docker-compose.yml file. In short, I needed to make some changes to make your package work inside of a container.
I LOVED your project because it is simple and effective, plus you already have a feature to load ENV vars described in the serverless.yml file inside the dev environment and it saves me some copy and paste. 
I wanted to take advantage of that and also continue to use Docker for my dev environment, however, when I was setting my Docker environment I realized that I couldn't span up a server to run inside a container because your Werkzeug runs the server by default on localhost and there isn't an option to change that. I needed to run the …
> Enables different host for the Werkzeug server

- wsgi.py
- wsgi_test.py
When `wsgi_encoding_dance ()`  is used, body character code is limited to decodeable character string with latin1.
e.g. 
```python
body = 'latin1_char'  # decodable
decoded = wsgi_encoding_dance(body)
body = 'テスト_char'  # unable to decode
decoded = wsgi_encoding_dance(body)
```
I confirmed this, worked with my app where I was experiencing this problem.
Sorry for my troublesome mother tongue in programming :'(
> Fix to support body's character code other than latin1

- wsgi.py
- wsgi_test.py
Not sure if this is the best way but i am using `serverless-wsgi` with `serverless-plugin-warmup` and `serverless-plugin-aws-alerts`
By default, the `serverless-plugin-warmup` triggers the handler without `headers` or `path` in the `event` variable so the lambda function always crash with key error thus triggering alert set by the `serverless-plugin-aws-alerts`. let me know if there is a better way to handle this.
Reference
https://www.npmjs.com/package/serverless-plugin-warmup
https://www.npmjs.com/package/serverless-plugin-aws-alerts
> handle request from serverless-plugin-warmup

- index.js
- wsgi.py
Hey, it is me again,
I ran into an issue while using zipping my dependencies using the python requirements plugin, as per their documentation we need to import a file created during the deploy process so we can use the zipped dependencies.
After getting tired of manually updating the wsgy.py on each deploy I decided to update my personal fork with the automated "solution" and open this PR so other people can benefit from that.
Cheers,
EM
> Enable zip dependencies when using the Python requirements plugin

- wsgi.py
For china AWS API Gateway is end with `.amzonaws.com.cn`.
I think better to remove the filter the host  on the specific url.
> remove specific AWS host

- index.js
- index.test.js
This PR adds hooks to build the wsgi handler in reaction to events defined by [`serverless-offline`](https://github.com/dherault/serverless-offline).
This will allow developers to use `serverless-wsgi` seamlessly (albeit w/ a performance hit) with `serverless-offline`. I'm open to suggestions on optimization.
> Add compatibility with serverless-offline

- wsgi.py
I think this may fix https://github.com/logandk/serverless-wsgi/issues/71.  I just ran into this as well.  I believe what is happening is the code is trying to import `serverless_wsgi` which then does these imports:
```
import base64
import os
import sys
from werkzeug.datastructures import Headers
from werkzeug.wrappers import Response
from werkzeug.urls import url_encode
from werkzeug._compat import BytesIO, string_types, to_bytes, wsgi_encoding_dance
```
and since werkzeug may still be zipped inside of `.requirements.zip`
> Import serverless_wsgi after unzipping requirements

- wsgi.py
When loaded app. having error such as missing import or syntax error, then `sls logs -t -f function_name` doesn't give any clue at all.
> Spit traceback to stdout when error loading app

- serverless_wsgi.py
- wsgi_handler_test.py
Last November API Gateway added support for multi-value parameters:
https://aws.amazon.com/blogs/compute/support-for-multi-value-parameters-in-amazon-api-gateway/
This adds support for those. However, with ALB whether you get them depends on a target group attribute, so we have to also retain support the old queryStringParameters event field:
https://serverless-training.com/articles/api-gateway-vs-application-load-balancer-technical-details/
Note: the same should really be done to headers but I don't need it. Also, since WSGI seems to require concatenating the header values with semicolons, that might actually break someone's current code, so it may require more thought.
> Support multi-value parameters

- index.js
- index.test.js
- serve.py
- serve_test.py
Updated the `serve` capabilities to allow for optionally running in multi-process mode and/or disabling threading. The default behavior was kept the same, where threading is enabled and the server uses a single process.
To optionally support a concurrency model that resembles that of API Gateway + Lambdas (where each request is routed to a separated Lambda container/instance) during local development.
* `pytest serve_test.py` tests pass
* `npm test` tests pass
* Was able to run a test project with threading and multi-process flags/options passed, verifying serialized and concurrent request handling when serving 100+ requests at once.
At the time of making this PR, the `master` branch has failing tests in `wsgi_handler_test.py`. Source: …
> Made threading optional and added support for multi-process mode

- wsgi_handler.py
- wsgi_handler_test.py
Because app.cli.main is replaced by click.core.main (I don't know why)
> Call flaskgroup main, not app.cli.main 

- README.md
- serverless_wsgi.py
When using CloudFront manually with the Origin set to the exact stage
URL, the WSGI application thinks that it is mounted at `/${stage}`
rather than `/`. This causes it to generate and return invalid URLs to
the user.
Example:
A CF distribution for `example.com` pointing at
`0deadbeef.execute-api.eu-west-1.amazonaws.com/production` should think
that `/foo` is mounted at `https://example.com/foo` not
`https://example.com/production/foo`
We need to fix this behaviour due to the assumption that all requests
with `amazonaws.com` in the Host header will contain the stage name in
the path. This is not true for CloudFront as it will send the `Host`
header of the origin, triggering our `if` clause.
> Allow use of CloudFront with a pre-set path

- README.md
Hi there,
Just spend a significant amount of time trying to deploy a WSGI application to our production API. However, it was not until I inspected the source code I figured out what exactly to put in the `API_GATEWAY_BASE_PATH` variable. I had a `/` first which caused the issue.
One could also consider battle-hardening the actual logic (https://github.com/logandk/serverless-wsgi/blob/master/serverless_wsgi.py#L113-L118) but I have not looked into that.
Either way, super excited about the WSGI plugin. Now I can run my Flask application everywhere!
> Improve API_GATEWAY_BASE_PATH documentation

- index.js
Errors from packaging requirements are dumped in hex values because child_process defaults to using a Buffer class, which serverless does not know to handle.
Using encoding option returns a string that makes sense to the user. E.g. (without virtualenv installed):
```
Serverless: Using Python specified in "runtime": python3.8
Serverless: Packaging Python WSGI handler...
Serverless: Packaging required Python packages...
Exception -----------------------------------------------
<Buffer 55 6e 61 62 6c 65 20 74 6f 20 6c 6f 61 64 20 76 69 72 74 75 61 6c 65 6e 76 2c 20 70 6c 65 61 73 65 20 69 6e 73 74 61 6c 6c 0a>
```
Turns into:
```
Serverless: Using Python specified in "runtime": python3.8
Serverless: Packaging Python WSGI handler...
Serverless: Packaging required Python packages...
Exception …
```
> Read stderr in utf8 so error messages are printed correctly

- serverless_wsgi.py
- wsgi_handler_test.py
This pull request addresses the query parameter issue we hit on using it with ALB. As mentioned in official document:
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html
> If the query parameters are URL-encoded, the load balancer does not decode them. You must decode them in your Lambda function. 
See also:
https://github.com/brefphp/bref/issues/456
This PR will decode query parameters correctly if the request is from ALB, regardless multi value support is enabled. This will fix query parameters with space (will be encoded to `%20`) and Unicode in ALB.
Also, `url_encode` in should natively support iteration on the `multiValueQueryStringParameters` since Werkzeug 0.3, so I remove the unnecessary `MultiDict` construction.
Also added tests for them.
(I …
> Fix the ALB query parameter handling.

- README.md
- serverless_wsgi.py
- wsgi_handler_test.py
This pull request provides support for the new HTTP API lambda proxy resp. Payload v2.0. 
As mentioned in the official document: 
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html
> Support for the new HTTP API lambda proxy resp. Payload v2.0

- serverless_wsgi.py
- wsgi_handler_test.py
This fixes #137 
Probably still requires some documentation at least. I'm also somewhat confused about the seemingly random use of u"strings", I just copied the other event mapping code so I have no idea if they are necessary or correct. I no longer have a working python 2 environment to test in.
This leaves all response mapping to the user. For example:
response:
headers:
Content-Type: "'application/json'"
template: '$input.path("$.body")'
statusCodes:
200:
pattern: ''
400:
pattern: '.*"statusCode": ?400.*'
500:
pattern: '.*"statusCode":.*'
An alternative would be to do the simple thing by default, returning the body on 200 and raising `RuntimeException("[code] body")` otherwise. That would set the status codes automatically, but would not allow more advanced mapping per status code. …
> Add handler for lambda integration

- requirements.txt
- setup.py
In Werkzeug's [latest 2.0.0 release](https://werkzeug.palletsprojects.com/en/2.0.x/changes/#version-2-0-0), support for Python 2 was removed: https://github.com/pallets/werkzeug/pull/1693.
This means that the imports from `werkzeug._compat` in `serverless_wsgi.py` no longer work:
https://github.com/logandk/serverless-wsgi/blob/a1a1c557a9d81ed37cbfb089adc897ec760e78fb/serverless_wsgi.py#L18
This can be fixed by pinning the `werkzeug` dependency to a pre-v2.0.0 version until support for the `werkzeug._compat` module is no longer necessary.
> Pin werkzeug to v1.0.1

- README.md
Serverless Framework is at v2 and soon will be at v3, and afaik this plugin will remain supporting it well.
I've remove confusing version info from documentation
> Remove confusing version info

- serverless_wsgi.py
This PR is intended to address #184 
When the isBase64Encoded parameter is set to False, then the conditional check on line 169 will evaluate to False and False != None. The change ensures that the conditional will evaluate to True when the value is set to None or False.
> Updated conditional check for isBase64Encoded to handle False

- serverless_wsgi.py
- wsgi_handler_test.py
To accept multiple query parameters in HTTP API Payload V2 , simply use "rawQueryString".
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html
> apigateway-v2-payload - Fix handling multiple query parameters.

- .travis.yml
- requirements.txt
- serverless_wsgi.py
- setup.py
Resolves #179
Dropping support for Python 2, updating werkzeug version to >2, and version bumping this package to 2.0. This should resolve any compatibility issues with werkzeug <2. Tested working in my private AWS account.
> Dropping support for Python 2

- index.js
- index.test.js
In serverless 2.32, they appear to have changed the way that it gets the options from the plugins. 
These changes fixed my issues and I can once again run `serverless wsgi manage` against serverless version 2.55.0
> Fixing serverless-wsgi to work on >=2.32

- index.js
- serve.py
- serve_test.py
This PR is meant to resolves logandk/serverless-wsgi#166
I left the current flag `--ssl` as it is, so it will still create ssl certs 'adhoc'.
I added two new flags to the `sls wsgi serve` command. They are `--ssl-pri` and `--ssl-pub`. 
These flags take file paths to custom ssl certs that are to be used to serve the app locally over https. The syntax is `--ssl-pri ~/localhost-key.pem --ssl-pub ~/localhost.pem`. This will serve the app over https using these ssl certs. The ssl certs can be generated via a tool like [mkcert](https://github.com/FiloSottile/mkcert)
Also, updated the tests to keep the same code coverage as before.
> Custom ssl certs option for serve command

- index.js
I'm facing the same mentioned at this issue https://github.com/logandk/serverless-wsgi/issues/136. 
So, I made some changes to validate if "wsgi_handler.handler" is at subfolder.
Here is an example how I would like/need to use this plugin
```
functions:
api:
handler: api/wsgi_handler.handler
```
> Support handler located at subfolder

- index.js
- index.test.js
- package.json
Support for `package.include` is [deprecated on Serverless Framework side](https://serverless.com/framework/docs/deprecations#new-way-to-define-packaging-patterns) and is scheduled to be removed with v3
This PR ensures that plugin internally relies on `package.patterns` as first choice.
I've additionally added `serverless` as peer dependency and indicated minimal version which supports `package.patterns`
I believe this should be considered as breaking change (as will stop working with Framework versions below 2.32.0) and should be released as a new major
Additionally I've fixed promises handling in tests (they weren't returned which in some cases resulted in improper communication of failures)
> Upgrade to rely on `package.patterns`

- .eslintrc.js
- index.js
- index.test.js
- package-lock.json
- package.json
Fixes #197
On version [2.33.1](https://github.com/serverless/serverless/compare/v2.32.1...v2.33.1#diff-6c086ee13402d96696c25b8494cc0cac837b1d8346672c7eac19f7e705a36078), they changed from `console.log` to `process.stdout.write`
This overrides stdout and rewrites all of the `\\n` to `\n` and outputs over lines like it should. 
This isn't the greatest fix, there are still extraneous output, but this is done to the best of my ability and makes the reading it 100x better than current.
Also ran prettier and eslint on the project
> Fix return output

- serverless_wsgi.py
When using the `httpApi` integration in combination with the [Serverless Offline plugin](https://github.com/dherault/serverless-offline), the body may be `None`
Closes #220
> Handle event with None body emitted by Serverless Offline plugin

- serverless_wsgi.py
@logandk, This pull request will fix the following issue #200.
```
{
"statusCode": 404,
"headers": {
"Content-Type": "text/html; charset=utf-8",
"Content-Length": "232"
},
"body": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\n",
"isBase64Encoded": false
}
```
> Issue Fixed: The requested URL was not found on the server

- serverless_wsgi.py
On Scaleway at least, authorizer is often None:
"requestContext": {
"accountId": "",
"resourceId": "",
"stage": "",
"requestId": "",
"resourcePath": "",
"authorizer": None,
"httpMethod": "GET",
"apiId": ""
},
Also, `isBase64Encoded` is sometimes missing, while the rest of the event is obviously v1.
`multiValueHeaders` is often `None` instead of missing or `{}`.
> Fixes for Scaleway

- serverless_wsgi.py
Updated the deprecated `Werkzeug` functions to utilize `urllib` versions instead as per `Werkzeug` recommendation.
> BugFix Updated Deprecated Werkzeug Functions

- index.js
- index.test.js
Fixes logandk/serverless-wsgi#255
Issue: In `invokeHandler` , `console.log` was being captured to get string response from lambda invocation, but when being used for manage commands, nothing was actually getting captured by `console.log`, the JSON parsing of the output would fail since it was parsing an empty string, and the command would always return with 0 status code instead of a 1 as expected for failed commands. 
This uses the temporary stdout override already in place to capture the return string from the lambda.
> Bugfix: Update lambda response processing

- .eslintrc.js
- index.js
- index.test.js
It now supports the --function and -f switches. If either switch is used in the command ```sls wsgi manage --function <function_name> or -f <function_name>```, it will take that function name. If the specified function is not found, it will throw an error, which is handled in invokeHandler. If neither switch is present, it will return the first function with the condition handler: wsgi_handler.handler, as it did before. Let me know if you need any more changes/help!
> Resolve / #244 
